### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by cflixdev-projects** [CodingCraftYT/Flask-App#1]
When trying to deploy the program, it says Error: Unable to find any supported Python versions. And when it runs  it shows an error 404 page in vercel.

**Comment by CodingCraftYT** [comment]
Go to the settings of your current project -> scroll down -> change the
nodejs version from "20.x" to "18.x"

**Comment by cflixdev-projects** [comment]
Thanks, this worked. Would u happen to know if selenium is supported in Vercel?

**Comment by CodingCraftYT** [comment]
Yes, it is supported but it can be more challenging.

If you need my help, I will provide my best support to you.

**Comment by cflixdev-projects** [comment]
So when deploying my program with selenium this issues faces:

-> /lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/vc__handler__python.py", line 13, in <module>
    __vc_spec.loader.exec_module(__vc_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./app.py", line 12, in <module>
    driver = webdriver.Chrome(options=options)
  File "/var/task/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/var/task/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
  File "/var/task/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from errINIT_REPORT Init Duration: 5560.53 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
[WARNING]	2024-04-03T17:56:34.415Z		Cache folder (/home/sbx_user1051/.cache/selenium) cannot be created: Read-only file system (os error 30)
[WARNING]	2024-04-03T17:56:34.415Z		Cache folder (/home/sbx_user1051/.cache/selenium) cannot be created: Read-only file system (os error 30)
[WARNING]	2024-04-03T17:56:34.415Z		Cache folder (/home/sbx_user1051/.cache/selenium) cannot be created: Read-only file system (os error 30)
[WARNING]	2024-04-03T17:56:34.415Z		Cache folder (/home/sbx_user1051/.cache/selenium) cannot be created: Read-only file system (os error 30)
[WARNING]	2024-04-03T17:56:34.415Z		Cache folder (/home/sbx_user1051/.cache/selenium) cannot be created: Read-only file system (os error 30)
[ERROR] NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/vc__handler__python.py", line 13, in <module>
    __vc_spec.loader.exec_module(__vc_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./app.py", line 12, in <module>
    driver = webdriver.Chrome(options=options)
  File "/var/task/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/var/task/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
  File "/var/task/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from errINIT_REPORT Init Duration: 9635.02 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Unknown application error occurred 

from what I understand I need to give permission to the cache files or change the cache path? how exactly would I implement the fix?

**Comment by CodingCraftYT** [comment]
From the following errors, I think there is a problem obtaining Chrome
driver for selenium within your environment.

My suggestion is that Vercel is only suitable for static websites, it is
not well supported for dynamic pages if we use Python with it.

**Comment by cflixdev-projects** [comment]
Do u know (free) alternatives where I could host my Website (including dynamic elements  & flask) so it would work?

**Comment by CodingCraftYT** [comment]
You can either buy the domains or use aws or google cloud to run your
application.
